allow_very_unsafe_file_sharing: true
cache_folder: /tmp
alignments:
  datasets:
    ibc:
      name: FUGW on IBC
      path: /home/alexis/singbrain/data/bc-alignments/ibc-alignments/data.csv
    monkey:
      name: Inter-species
      path: /home/alexis/singbrain/data/bc-alignments/monkey-alignments/data.csv
surfaces:
  datasets:
    ibc:
      name: Individual Brain Charting
      path: /home/alexis/singbrain/data/mathlang_rsvp_fs5_fs7_individual_db/result_db.csv
      descriptions: /home/alexis/singbrain/data/ibc_descriptions.json
      default_mesh: pial
      other_meshes:
        - infl
        - white
