name: Build brain-cockpit front end

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build front-end
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            node_version: "14"
          - os: ubuntu-latest
            node_version: "16"
          - os: ubuntu-latest
            node_version: "18"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: web

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: web
