name: Build brain-cockpit front end

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build front-end
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: web

      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: web
